import React, { createContext, useContext, useState, useEffect } from "react";

export const translations = {
    English: {
        // Sidebar
        dashboard: "Dashboard",
        newAnalysis: "New Analysis",
        testHistory: "Test History",
        reports: "Reports",

        // AppHeader
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",

        // Dashboard
        dashboardLabel: "DASHBOARD",
        goodDay: "Good day",
        dashboardSubtitle: "Here's your real-time quality analysis overview.",
        newAnalysisBtn: "New Analysis",
        totalTests: "Total Tests",
        goodQuality: "Good Quality",
        averageQuality: "Average Quality",
        poorQuality: "Poor Quality",
        completedTests: "completed tests",
        noTestsYet: "No tests yet",
        ofTotalTests: "% of total tests",
        recentTests: "Recent Tests",
        latestAnalyses: "Your latest quality analyses",
        viewAll: "View All",
        noRecentTests: "No recent tests found.",
        startFirstTest: "Start your first test",
        qualityOverview: "Quality Overview",
        testDistribution: "Current test distribution",
        tests: "Tests",
        good: "Good",
        average: "Average",
        poor: "Poor",
        qualityTip: "Quality Monitoring Tip",
        qualityTipText: "Regularly monitor moisture, pH and storage conditions along with visual quality indicators.",

        // Profile Page
        accountLabel: "ACCOUNT",
        myProfile: "My Profile",
        profileSubtitle: "Manage your farmer account and farm information.",
        fullName: "Full Name",
        emailReadOnly: "Email (Read-only)",
        mobileNumber: "Mobile Number",
        farmInformation: "Farm Information",
        saveChanges: "Save Changes",
        savingChanges: "Saving Changes...",
        profileUpdated: "Profile updated successfully!",
        enterFullName: "Enter your full name",
        enterMobile: "Enter mobile number",
        enterFarmInfo: "Enter details about your farm, location, or cattle herd",

        // Settings section on Profile page
        settingsSection: "Settings",
        languageSection: "Language",
        languageSectionDesc: "Choose your preferred language for the entire app.",
        notificationsLabel: "Notifications",
        notificationsDesc: "Receive quality analysis notifications.",
        offlineModeLabel: "Offline Mode",
        offlineModeDesc: "Store tests locally when offline.",
        settingsSaved: "Settings saved!",

        // Settings Page
        settingsLabel: "SETTINGS",
        appSettings: "Application Settings",
        customizeExperience: "Customize your AgriFeed AI experience.",
        chooseLanguage: "Choose your preferred language.",

        // Sample Selection
        newAnalysisLabel: "NEW ANALYSIS",
        whatToAnalyze: "What would you like to analyze?",
        selectSampleType: "Select the type of sample you want to evaluate.",
        feed: "Feed",
        feedDesc: "Analyze feed quality using an image and optional measurements such as moisture, protein and fiber.",
        startFeedAnalysis: "Start Feed Analysis",
        silage: "Silage",
        silageDesc: "Analyze silage condition using visual characteristics and readings such as pH, moisture and temperature.",
        startSilageAnalysis: "Start Silage Analysis",
        backToDashboard: "Dashboard",
        changeSample: "Change Sample",

        // Feed Analysis
        feedAnalysisLabel: "FEED ANALYSIS",
        analyzeFeedQuality: "Analyze Feed Quality",
        feedAnalysisDesc: "Upload your feed sample image for automated Google Gemini 3.1 Pro visual defect detection (mould, discoloration, foreign material) and evaluate chemical safety parameters.",
        fullAssessmentImage: "Full Assessment Sample Image",
        required: "Required",
        uploadFeedImageHint: "Upload a clear, well-lit image of the feed sample for your permanent test report.",
        clickToUploadFeed: "Click to upload feed image",
        imageFormatHint: "PNG, JPG or JPEG — max 15MB",
        imageRequired: "A sample image is required before analyzing.",
        changeImage: "Change Image",
        chooseImageFile: "Choose Image File",
        useCamera: "Use Camera",
        testReadings: "Test Readings & Parameters",
        optionalReadings: "Optional — enter available laboratory readings.",
        moisture: "Moisture (%)",
        crudeProtein: "Crude Protein (%)",
        crudeFiber: "Crude Fiber (%)",
        aflatoxin: "Aflatoxin (ppb)",
        phValue: "pH Value",
        feedInfoBox: "Test readings are optional. The system can perform preliminary screening without them.",
        generateReport: "Generate Full Report",
        analyzingFeed: "Analyzing Feed & Generating Report...",
        uploadToEnable: "Upload a sample image to enable report generation",

        // Silage Analysis
        silageAnalysisLabel: "SILAGE ANALYSIS",
        analyzeSilageQuality: "Analyze Silage Quality",
        silageAnalysisDesc: "Upload your silage sample image for automated Google Gemini 3.1 Pro visual defect detection (mould, discoloration, foreign material) and evaluate chemical safety parameters.",
        uploadSilageImageHint: "Upload a clear, well-lit image of the silage sample for your permanent test report.",
        clickToUploadSilage: "Click to upload silage image",
        pitTemperature: "Pit Temperature (°C)",
        silageInfoBox: "The result is a preliminary screening and should not replace laboratory testing.",
        analyzingSilage: "Analyzing Silage & Generating Report...",

        // Report Page
        reportsLabel: "REPORTS",
        analysisReports: "Analysis Reports",
        reportsSubtitle: "Download official PDF quality & safety assessment reports.",
        noReports: "No reports generated yet. Perform a new analysis to create a report.",
        feedQualityReport: "Feed Quality Report",
        silageQualityReport: "Silage Quality Report",
        testId: "Test ID",
        downloadPDF: "Download PDF",
        generatingPDF: "Generating PDF...",

        // Landing Page
        features: "Features",
        howItWorks: "How It Works",
        about: "About",
        login: "Login",
        getStarted: "Get Started",
        heroHeadline1: "Smarter Feed.",
        heroHeadline2: "Healthier Cattle.",
        heroHeadline3: "Better Decisions.",
        heroDesc: "Analyze cattle feed and silage quality using AI-powered image analysis and test readings. Get simple and actionable recommendations for your farm.",
        startAnalyzing: "Start Analyzing",
        learnMore: "Learn More",
        featuresLabel: "FEATURES",
        featuresHeading: "Everything you need for quality assessment",
        featuresSubheading: "A simple digital platform designed to make feed and silage assessment easier.",
        imageAnalysis: "Image Analysis",
        imageAnalysisDesc: "Upload or capture sample images for AI-based visual analysis.",
        aiClassification: "AI Classification",
        aiClassificationDesc: "Classify feed and silage conditions using trained computer vision models.",
        qualityEvaluation: "Quality Evaluation",
        qualityEvaluationDesc: "Combine AI results with optional test readings for comprehensive scoring.",
        reportsHistory: "Reports & History",
        reportsHistoryDesc: "Track previous tests and monitor quality trends over time.",
        howItWorksLabel: "HOW IT WORKS",
        fromSampleToRec: "From sample to recommendation",
        step1Title: "Upload Sample",
        step1Desc: "Capture or upload a feed or silage image.",
        step2Title: "AI Analysis",
        step2Desc: "The AI model analyzes visible characteristics.",
        step3Title: "Quality Check",
        step3Desc: "AI findings and readings are evaluated together.",
        step4Title: "Get Advice",
        step4Desc: "Receive a simple result and recommendation.",
        ctaHeading: "Ready to analyze your sample?",
        ctaSubheading: "Start your digital feed and silage quality assessment today.",
        footerRight: "AI-Based Feed & Silage Quality Analysis",

        // Language switcher in header
        selectLanguage: "Language",

        // Login page
        backToHome: "← Back to home",
        welcomeBack: "Welcome back",
        loginSubtitle: "Sign in to continue analyzing feed and silage quality.",
        emailOrMobile: "Email or Mobile Number",
        password: "Password",
        rememberMe: "Remember me",
        signIn: "Sign In",
        signingIn: "Signing in...",
        noAccount: "Don't have an account?",
        createAccount: "Create account",
        loginTagline1: "Better quality.",
        loginTagline2: "Better decisions.",
        loginTaglineDesc: "Use AI-powered analysis to understand your feed and silage quality quickly and effectively.",
        enterEmailOrMobile: "you@example.com or mobile number",
        enterPassword: "Enter your password",

        // Register page
        createYourAccount: "Create your account",
        registerSubtitle: "Start analyzing feed and silage quality.",
        emailAddress: "Email Address",
        optionalLabel: "(Optional)",
        confirmPassword: "Confirm Password",
        reenterPassword: "Re-enter your password",
        createPasswordHint: "Create a password (min 6 characters)",
        creatingAccount: "Creating account...",
        createAccountBtn: "Create Account",
        alreadyHaveAccount: "Already have an account?",
        signInLink: "Sign in",
        registerTagline1: "Better feed",
        registerTagline2: "starts with",
        registerTagline3: "better insight.",
        registerTaglineDesc: "Use AI-powered analysis to understand feed and silage quality with simple, farmer-friendly recommendations.",

        // Analysis Result page
        analysisComplete: "ANALYSIS COMPLETE",
        testIdLabel: "TEST ID",
        qualityAnalysisResult: "Quality Analysis Result",
        feedSampleEvaluated: "Your feed sample has been evaluated across all quality & safety parameters.",
        silageSampleEvaluated: "Your silage sample has been evaluated across all quality & safety parameters.",
        overallQuality: "Overall Quality",
        aiVisualScreening: "AI Visual Anomaly & Defect Screening",
        visualStatus: "VISUAL STATUS",
        mould: "MOULD",
        discolor: "DISCOLOR",
        foreignMat: "FOREIGN MAT.",
        total: "TOTAL",
        detectedAnomalies: "Detected Anomalies",
        anomaly: "Anomaly",
        confidence: "Confidence",
        location: "Location",
        measuredParameters: "Measured Parameters",
        noReadingsEntered: "No physical readings entered. Screening based on visual parameters.",
        moistureLabel: "Moisture",
        crudeProteinLabel: "Crude Protein",
        crudeFiberLabel: "Crude Fiber",
        aflatoxinLabel: "Aflatoxin (ppb)",
        phLevelLabel: "pH Level",
        temperatureLabel: "Temperature",
        warningLabel: "(Warning)",
        safeLabel: "(Safe)",
        recommendations: "RECOMMENDATIONS",
        sampleSuitable: "Sample appears suitable based on available inputs.",
        viewDetailedAdvisory: "View Detailed Advisory",
        newAnalysisBtn2: "New Analysis",
        downloadPDFReport: "Download PDF Report",
        generatingPDFBtn: "Generating PDF...",

        // Advisory / Recommendations
        advisoryLabel: "ADVISORY",
        advisoryHeading: "Recommendations",
        advisorySubtitle: "Practical guidance based on",
        advisoryYourResults: "your analysis results",
        currentAssessment: "Current Assessment",
        qualityWord: "Quality",
        recommendationNum: "Recommendation",
        importantCardTitle: "Important",
        importantCardDesc: "This application provides preliminary screening and advisory information. It does not replace laboratory testing for detailed nutritional or toxin analysis.",
        tipCardTitle: "Quality Monitoring Tip",
        tipCardDesc: "Maintain records of feed and silage quality over time to identify recurring storage or handling issues.",
        defaultAdvice1Title: "Continue proper storage",
        defaultAdvice1Desc: "Keep feed protected from excessive moisture and unsuitable storage conditions.",
        defaultAdvice2Title: "Monitor quality regularly",
        defaultAdvice2Desc: "Perform regular visual checks and record available measurements to identify seasonal trends.",
        defaultAdvice3Title: "Confirm suspected problems",
        defaultAdvice3Desc: "If mould, spoilage or contamination is suspected, consider appropriate laboratory confirmatory testing.",
    },

    Hindi: {
        // Sample Selection
        newAnalysisLabel: "नया विश्लेषण",
        whatToAnalyze: "आप क्या विश्लेषण करना चाहते हैं?",
        selectSampleType: "उस नमूने का प्रकार चुनें जिसे आप मूल्यांकन करना चाहते हैं।",
        feed: "चारा",
        feedDesc: "नमी, प्रोटीन और फाइबर जैसी वैकल्पिक मापों के साथ एक छवि का उपयोग करके चारे की गुणवत्ता का विश्लेषण करें।",
        startFeedAnalysis: "चारा विश्लेषण शुरू करें",
        silage: "साइलेज",
        silageDesc: "pH, नमी और तापमान जैसी रीडिंग के साथ दृश्य विशेषताओं का उपयोग करके साइलेज स्थिति का विश्लेषण करें।",
        startSilageAnalysis: "साइलेज विश्लेषण शुरू करें",
        backToDashboard: "डैशबोर्ड",
        changeSample: "नमूना बदलें",
        feedAnalysisLabel: "चारा विश्लेषण",
        analyzeFeedQuality: "चारे की गुणवत्ता का विश्लेषण करें",
        feedAnalysisDesc: "स्वचालित दृश्य दोष पहचान (फफूंद, मलिनकिरण, विदेशी सामग्री) के लिए अपनी चारे की नमूना छवि अपलोड करें।",
        fullAssessmentImage: "पूर्ण मूल्यांकन नमूना छवि",
        required: "आवश्यक",
        uploadFeedImageHint: "अपनी स्थायी परीक्षण रिपोर्ट के लिए चारे के नमूने की स्पष्ट, अच्छी रोशनी वाली छवि अपलोड करें।",
        clickToUploadFeed: "चारे की छवि अपलोड करने के लिए क्लिक करें",
        imageFormatHint: "PNG, JPG या JPEG — अधिकतम 15MB",
        imageRequired: "विश्लेषण से पहले एक नमूना छवि आवश्यक है।",
        changeImage: "छवि बदलें",
        chooseImageFile: "छवि फ़ाइल चुनें",
        useCamera: "कैमरा उपयोग करें",
        testReadings: "परीक्षण रीडिंग और पैरामीटर",
        optionalReadings: "वैकल्पिक — उपलब्ध प्रयोगशाला रीडिंग दर्ज करें।",
        moisture: "नमी (%)",
        crudeProtein: "कच्चा प्रोटीन (%)",
        crudeFiber: "कच्चा फाइबर (%)",
        aflatoxin: "एफ्लाटॉक्सिन (ppb)",
        phValue: "pH मूल्य",
        feedInfoBox: "परीक्षण रीडिंग वैकल्पिक हैं। सिस्टम उनके बिना प्रारंभिक स्क्रीनिंग कर सकता है।",
        generateReport: "पूरी रिपोर्ट तैयार करें",
        analyzingFeed: "चारे का विश्लेषण और रिपोर्ट तैयार हो रही है...",
        uploadToEnable: "रिपोर्ट तैयार करने के लिए नमूना छवि अपलोड करें",
        silageAnalysisLabel: "साइलेज विश्लेषण",
        analyzeSilageQuality: "साइलेज गुणवत्ता का विश्लेषण करें",
        silageAnalysisDesc: "स्वचालित दृश्य दोष पहचान के लिए अपनी साइलेज नमूना छवि अपलोड करें।",
        uploadSilageImageHint: "अपनी स्थायी परीक्षण रिपोर्ट के लिए साइलेज नमूने की स्पष्ट छवि अपलोड करें।",
        clickToUploadSilage: "साइलेज छवि अपलोड करने के लिए क्लिक करें",
        pitTemperature: "गड्ढे का तापमान (°C)",
        silageInfoBox: "परिणाम एक प्रारंभिक स्क्रीनिंग है और प्रयोगशाला परीक्षण की जगह नहीं ले सकता।",
        analyzingSilage: "साइलेज का विश्लेषण और रिपोर्ट तैयार हो रही है...",
        reportsLabel: "रिपोर्ट",
        analysisReports: "विश्लेषण रिपोर्ट",
        reportsSubtitle: "आधिकारिक PDF गुणवत्ता और सुरक्षा मूल्यांकन रिपोर्ट डाउनलोड करें।",
        noReports: "अभी तक कोई रिपोर्ट तैयार नहीं हुई। रिपोर्ट बनाने के लिए नया विश्लेषण करें।",
        feedQualityReport: "चारा गुणवत्ता रिपोर्ट",
        silageQualityReport: "साइलेज गुणवत्ता रिपोर्ट",
        testId: "परीक्षण आईडी",
        downloadPDF: "PDF डाउनलोड करें",
        generatingPDF: "PDF तैयार हो रही है...",

        // Language switcher
        selectLanguage: "भाषा",

        // Login
        backToHome: "← होम पर वापस",
        welcomeBack: "वापस स्वागत है",
        loginSubtitle: "फ़ीड और साइलेज गुणवत्ता का विश्लेषण जारी रखने के लिए साइन इन करें।",
        emailOrMobile: "ईमेल या मोबाइल नंबर",
        password: "पासवर्ड",
        rememberMe: "मुझे याद रखें",
        signIn: "साइन इन",
        signingIn: "साइन इन हो रहा है...",
        noAccount: "खाता नहीं है?",
        createAccount: "खाता बनाएं",
        loginTagline1: "बेहतर गुणवत्ता।",
        loginTagline2: "बेहतर निर्णय।",
        loginTaglineDesc: "अपने चारे और साइलेज की गुणवत्ता को जल्दी और प्रभावी ढंग से समझने के लिए AI-संचालित विश्लेषण का उपयोग करें।",
        enterEmailOrMobile: "you@example.com या मोबाइल नंबर",
        enterPassword: "अपना पासवर्ड दर्ज करें",

        // Register
        createYourAccount: "अपना खाता बनाएं",
        registerSubtitle: "फ़ीड और साइलेज गुणवत्ता का विश्लेषण शुरू करें।",
        emailAddress: "ईमेल पता",
        optionalLabel: "(वैकल्पिक)",
        confirmPassword: "पासवर्ड की पुष्टि करें",
        reenterPassword: "अपना पासवर्ड पुनः दर्ज करें",
        createPasswordHint: "पासवर्ड बनाएं (न्यूनतम 6 अक्षर)",
        creatingAccount: "खाता बनाया जा रहा है...",
        createAccountBtn: "खाता बनाएं",
        alreadyHaveAccount: "पहले से खाता है?",
        signInLink: "साइन इन करें",
        registerTagline1: "बेहतर चारा",
        registerTagline2: "शुरू होता है",
        registerTagline3: "बेहतर अंतर्दृष्टि से।",
        registerTaglineDesc: "सरल, किसान-अनुकूल सिफारिशों के साथ चारे और साइलेज की गुणवत्ता समझें।",

        // Analysis Result
        analysisComplete: "विश्लेषण पूर्ण",
        testIdLabel: "परीक्षण आईडी",
        qualityAnalysisResult: "गुणवत्ता विश्लेषण परिणाम",
        feedSampleEvaluated: "आपके चारे के नमूने का सभी गुणवत्ता और सुरक्षा मापदंडों पर मूल्यांकन किया गया है।",
        silageSampleEvaluated: "आपके साइलेज नमूने का सभी गुणवत्ता और सुरक्षा मापदंडों पर मूल्यांकन किया गया है।",
        overallQuality: "समग्र गुणवत्ता",
        aiVisualScreening: "AI दृश्य विसंगति और दोष स्क्रीनिंग",
        visualStatus: "दृश्य स्थिति",
        mould: "फफूंद",
        discolor: "रंग बदलाव",
        foreignMat: "विदेशी सामग्री",
        total: "कुल",
        detectedAnomalies: "पता लगाई गई विसंगतियाँ",
        anomaly: "विसंगति",
        confidence: "विश्वास",
        location: "स्थान",
        measuredParameters: "मापे गए मापदंड",
        noReadingsEntered: "कोई भौतिक रीडिंग दर्ज नहीं। दृश्य मापदंडों पर आधारित स्क्रीनिंग।",
        moistureLabel: "नमी",
        crudeProteinLabel: "कच्चा प्रोटीन",
        crudeFiberLabel: "कच्चा फाइबर",
        aflatoxinLabel: "एफ्लाटॉक्सिन (ppb)",
        phLevelLabel: "pH स्तर",
        temperatureLabel: "तापमान",
        warningLabel: "(चेतावनी)",
        safeLabel: "(सुरक्षित)",
        recommendations: "सिफ़ारिशें",
        sampleSuitable: "उपलब्ध इनपुट के आधार पर नमूना उपयुक्त लगता है।",
        viewDetailedAdvisory: "विस्तृत सलाह देखें",
        newAnalysisBtn2: "नया विश्लेषण",
        downloadPDFReport: "PDF रिपोर्ट डाउनलोड करें",
        generatingPDFBtn: "PDF तैयार हो रही है...",

        dashboard: "डैशबोर्ड",
        newAnalysis: "नया विश्लेषण",
        testHistory: "परीक्षण इतिहास",
        reports: "रिपोर्ट",
        profile: "प्रोफ़ाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        dashboardLabel: "डैशबोर्ड",
        goodDay: "नमस्ते",
        dashboardSubtitle: "यहाँ आपका रीयल-टाइम गुणवत्ता विश्लेषण अवलोकन है।",
        newAnalysisBtn: "नया विश्लेषण",
        totalTests: "कुल परीक्षण",
        goodQuality: "अच्छी गुणवत्ता",
        averageQuality: "औसत गुणवत्ता",
        poorQuality: "खराब गुणवत्ता",
        completedTests: "पूर्ण परीक्षण",
        noTestsYet: "अभी कोई परीक्षण नहीं",
        ofTotalTests: "% कुल परीक्षणों का",
        recentTests: "हालिया परीक्षण",
        latestAnalyses: "आपके नवीनतम गुणवत्ता विश्लेषण",
        viewAll: "सभी देखें",
        noRecentTests: "कोई हालिया परीक्षण नहीं मिला।",
        startFirstTest: "अपना पहला परीक्षण शुरू करें",
        qualityOverview: "गुणवत्ता अवलोकन",
        testDistribution: "वर्तमान परीक्षण वितरण",
        tests: "परीक्षण",
        good: "अच्छा",
        average: "औसत",
        poor: "खराब",
        qualityTip: "गुणवत्ता निगरानी सुझाव",
        qualityTipText: "दृश्य गुणवत्ता संकेतकों के साथ नमी, पीएच और भंडारण स्थितियों की नियमित निगरानी करें।",
        accountLabel: "खाता",
        myProfile: "मेरी प्रोफ़ाइल",
        profileSubtitle: "अपने किसान खाते और खेत की जानकारी प्रबंधित करें।",
        fullName: "पूरा नाम",
        emailReadOnly: "ईमेल (केवल पढ़ें)",
        mobileNumber: "मोबाइल नंबर",
        farmInformation: "खेत की जानकारी",
        saveChanges: "परिवर्तन सहेजें",
        savingChanges: "सहेज रहा है...",
        profileUpdated: "प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!",
        enterFullName: "अपना पूरा नाम दर्ज करें",
        enterMobile: "मोबाइल नंबर दर्ज करें",
        enterFarmInfo: "अपने खेत, स्थान या पशु झुंड के बारे में जानकारी दर्ज करें",
        settingsSection: "सेटिंग्स",
        languageSection: "भाषा",
        languageSectionDesc: "पूरे ऐप के लिए अपनी पसंदीदा भाषा चुनें।",
        notificationsLabel: "सूचनाएं",
        notificationsDesc: "गुणवत्ता विश्लेषण सूचनाएं प्राप्त करें।",
        offlineModeLabel: "ऑफलाइन मोड",
        offlineModeDesc: "ऑफलाइन होने पर परीक्षण स्थानीय रूप से संग्रहीत करें।",
        settingsSaved: "सेटिंग्स सहेजी गईं!",
        settingsLabel: "सेटिंग्स",
        appSettings: "एप्लिकेशन सेटिंग्स",
        customizeExperience: "अपना AgriFeed AI अनुभव अनुकूलित करें।",
        chooseLanguage: "अपनी पसंदीदा भाषा चुनें।",
        features: "सुविधाएं",
        howItWorks: "यह कैसे काम करता है",
        about: "हमारे बारे में",
        login: "लॉग इन",
        getStarted: "शुरू करें",
        heroHeadline1: "स्मार्ट चारा।",
        heroHeadline2: "स्वस्थ पशु।",
        heroHeadline3: "बेहतर निर्णय।",
        heroDesc: "AI-संचालित छवि विश्लेषण और परीक्षण रीडिंग का उपयोग करके पशु चारे और साइलेज गुणवत्ता का विश्लेषण करें। अपने खेत के लिए सरल और कार्रवाई योग्य सिफारिशें प्राप्त करें।",
        startAnalyzing: "विश्लेषण शुरू करें",
        learnMore: "और जानें",
        featuresLabel: "सुविधाएं",
        featuresHeading: "गुणवत्ता आकलन के लिए सब कुछ",
        featuresSubheading: "चारे और साइलेज आकलन को आसान बनाने के लिए एक सरल डिजिटल प्लेटफॉर्म।",
        imageAnalysis: "छवि विश्लेषण",
        imageAnalysisDesc: "AI-आधारित दृश्य विश्लेषण के लिए नमूना छवियां अपलोड या कैप्चर करें।",
        aiClassification: "AI वर्गीकरण",
        aiClassificationDesc: "प्रशिक्षित कंप्यूटर विज़न मॉडल का उपयोग करके चारे और साइलेज स्थितियों को वर्गीकृत करें।",
        qualityEvaluation: "गुणवत्ता मूल्यांकन",
        qualityEvaluationDesc: "व्यापक स्कोरिंग के लिए AI परिणामों को वैकल्पिक परीक्षण रीडिंग के साथ जोड़ें।",
        reportsHistory: "रिपोर्ट और इतिहास",
        reportsHistoryDesc: "पिछले परीक्षणों को ट्रैक करें और समय के साथ गुणवत्ता प्रवृत्तियों की निगरानी करें।",
        howItWorksLabel: "यह कैसे काम करता है",
        fromSampleToRec: "नमूने से सिफारिश तक",
        step1Title: "नमूना अपलोड करें",
        step1Desc: "चारे या साइलेज की छवि कैप्चर या अपलोड करें।",
        step2Title: "AI विश्लेषण",
        step2Desc: "AI मॉडल दृश्य विशेषताओं का विश्लेषण करता है।",
        step3Title: "गुणवत्ता जांच",
        step3Desc: "AI निष्कर्षों और रीडिंग का एक साथ मूल्यांकन किया जाता है।",
        step4Title: "सलाह प्राप्त करें",
        step4Desc: "एक सरल परिणाम और सिफारिश प्राप्त करें।",
        ctaHeading: "अपने नमूने का विश्लेषण करने के लिए तैयार हैं?",
        ctaSubheading: "आज ही अपना डिजिटल चारा और साइलेज गुणवत्ता आकलन शुरू करें।",
        footerRight: "AI-आधारित चारा और साइलेज गुणवत्ता विश्लेषण",

        // Advisory / Recommendations
        advisoryLabel: "परामर्श",
        advisoryHeading: "सिफारिशें",
        advisorySubtitle: "के आधार पर व्यावहारिक मार्गदर्शन",
        advisoryYourResults: "आपके विश्लेषण परिणाम",
        currentAssessment: "वर्तमान मूल्यांकन",
        qualityWord: "गुणवत्ता",
        recommendationNum: "सिफारिश",
        importantCardTitle: "महत्वपूर्ण",
        importantCardDesc: "यह एप्लिकेशन प्रारंभिक स्क्रीनिंग और सलाह संबंधी जानकारी प्रदान करता है। यह विस्तृत पोषण या विष विश्लेषण के लिए प्रयोगशाला परीक्षण की जगह नहीं लेता है।",
        tipCardTitle: "गुणवत्ता निगरानी सुझाव",
        tipCardDesc: "आवर्ती भंडारण या हैंडलिंग समस्याओं की पहचान करने के लिए समय के साथ चारे और साइलेज गुणवत्ता का रिकॉर्ड बनाए रखें।",
        defaultAdvice1Title: "उचित भंडारण जारी रखें",
        defaultAdvice1Desc: "चारे को अत्यधिक नमी और अनुपयुक्त भंडारण स्थितियों से सुरक्षित रखें।",
        defaultAdvice2Title: "नियमित रूप से गुणवत्ता की निगरानी करें",
        defaultAdvice2Desc: "मौसमी रुझानों की पहचान करने के लिए नियमित दृश्य जांच करें और उपलब्ध रीडिंग रिकॉर्ड करें।",
        defaultAdvice3Title: "संदेहास्पद समस्याओं की पुष्टि करें",
        defaultAdvice3Desc: "यदि फफूंद, खराबी या संदूषण का संदेह हो, तो उचित प्रयोगशाला पुष्टिकरण परीक्षण पर विचार करें।",
    },

    Marathi: {
        // Sample Selection
        newAnalysisLabel: "नवीन विश्लेषण",
        whatToAnalyze: "तुम्हाला काय विश्लेषण करायचे आहे?",
        selectSampleType: "तुम्हाला मूल्यांकन करायच्या नमुन्याचा प्रकार निवडा.",
        feed: "चारा",
        feedDesc: "ओलावा, प्रथिने आणि तंतू यांसारख्या वैकल्पिक मोजमापांसह प्रतिमा वापरून चाऱ्याच्या गुणवत्तेचे विश्लेषण करा.",
        startFeedAnalysis: "चारा विश्लेषण सुरू करा",
        silage: "सायलेज",
        silageDesc: "pH, ओलावा आणि तापमान यांसारख्या रीडिंगसह दृश्य वैशिष्ट्ये वापरून सायलेज स्थितीचे विश्लेषण करा.",
        startSilageAnalysis: "सायलेज विश्लेषण सुरू करा",
        backToDashboard: "डॅशबोर्ड",
        changeSample: "नमुना बदला",
        feedAnalysisLabel: "चारा विश्लेषण",
        analyzeFeedQuality: "चाऱ्याच्या गुणवत्तेचे विश्लेषण करा",
        feedAnalysisDesc: "स्वयंचलित दृश्य दोष शोधासाठी (बुरशी, रंग बदल, परकीय साहित्य) तुमची चारा नमुना प्रतिमा अपलोड करा.",
        fullAssessmentImage: "संपूर्ण मूल्यांकन नमुना प्रतिमा",
        required: "आवश्यक",
        uploadFeedImageHint: "तुमच्या कायमस्वरूपी चाचणी अहवालासाठी चाऱ्याच्या नमुन्याची स्पष्ट, चांगल्या प्रकाशात काढलेली प्रतिमा अपलोड करा.",
        clickToUploadFeed: "चारा प्रतिमा अपलोड करण्यासाठी क्लिक करा",
        imageFormatHint: "PNG, JPG किंवा JPEG — जास्तीत जास्त 15MB",
        imageRequired: "विश्लेषण करण्यापूर्वी नमुना प्रतिमा आवश्यक आहे.",
        changeImage: "प्रतिमा बदला",
        chooseImageFile: "प्रतिमा फाइल निवडा",
        useCamera: "कॅमेरा वापरा",
        testReadings: "चाचणी रीडिंग आणि पॅरामीटर्स",
        optionalReadings: "वैकल्पिक — उपलब्ध प्रयोगशाळा रीडिंग प्रविष्ट करा.",
        moisture: "ओलावा (%)",
        crudeProtein: "कच्चे प्रथिने (%)",
        crudeFiber: "कच्चे तंतू (%)",
        aflatoxin: "अफ्लाटॉक्सिन (ppb)",
        phValue: "pH मूल्य",
        feedInfoBox: "चाचणी रीडिंग वैकल्पिक आहेत. सिस्टम त्यांच्याशिवाय प्राथमिक तपासणी करू शकते.",
        generateReport: "संपूर्ण अहवाल तयार करा",
        analyzingFeed: "चाऱ्याचे विश्लेषण आणि अहवाल तयार होत आहे...",
        uploadToEnable: "अहवाल तयार करण्यासाठी नमुना प्रतिमा अपलोड करा",
        silageAnalysisLabel: "सायलेज विश्लेषण",
        analyzeSilageQuality: "सायलेज गुणवत्तेचे विश्लेषण करा",
        silageAnalysisDesc: "स्वयंचलित दृश्य दोष शोधासाठी तुमची सायलेज नमुना प्रतिमा अपलोड करा.",
        uploadSilageImageHint: "तुमच्या कायमस्वरूपी चाचणी अहवालासाठी सायलेज नमुन्याची स्पष्ट प्रतिमा अपलोड करा.",
        clickToUploadSilage: "सायलेज प्रतिमा अपलोड करण्यासाठी क्लिक करा",
        pitTemperature: "खड्ड्याचे तापमान (°C)",
        silageInfoBox: "निकाल हे प्राथमिक तपासणी आहे आणि प्रयोगशाळा चाचणी बदलू शकत नाही.",
        analyzingSilage: "सायलेजचे विश्लेषण आणि अहवाल तयार होत आहे...",
        reportsLabel: "अहवाल",
        analysisReports: "विश्लेषण अहवाल",
        reportsSubtitle: "अधिकृत PDF गुणवत्ता आणि सुरक्षा मूल्यांकन अहवाल डाउनलोड करा.",
        noReports: "अद्याप कोणताही अहवाल तयार केलेला नाही. अहवाल तयार करण्यासाठी नवीन विश्लेषण करा.",
        feedQualityReport: "चारा गुणवत्ता अहवाल",
        silageQualityReport: "सायलेज गुणवत्ता अहवाल",
        testId: "चाचणी आयडी",
        downloadPDF: "PDF डाउनलोड करा",
        generatingPDF: "PDF तयार होत आहे...",

        // Language switcher
        selectLanguage: "भाषा",

        // Login
        backToHome: "← होमवर परत",
        welcomeBack: "परत स्वागत आहे",
        loginSubtitle: "चारा आणि सायलेज गुणवत्ता विश्लेषण सुरू ठेवण्यासाठी साइन इन करा.",
        emailOrMobile: "ईमेल किंवा मोबाइल नंबर",
        password: "पासवर्ड",
        rememberMe: "मला लक्षात ठेवा",
        signIn: "साइन इन",
        signingIn: "साइन इन होत आहे...",
        noAccount: "खाते नाही?",
        createAccount: "खाते तयार करा",
        loginTagline1: "चांगली गुणवत्ता.",
        loginTagline2: "चांगले निर्णय.",
        loginTaglineDesc: "तुमच्या चारा आणि सायलेजची गुणवत्ता जलद आणि प्रभावीपणे समजण्यासाठी AI-चालित विश्लेषण वापरा.",
        enterEmailOrMobile: "you@example.com किंवा मोबाइल नंबर",
        enterPassword: "तुमचा पासवर्ड प्रविष्ट करा",

        // Register
        createYourAccount: "तुमचे खाते तयार करा",
        registerSubtitle: "चारा आणि सायलेज गुणवत्ता विश्लेषण सुरू करा.",
        emailAddress: "ईमेल पत्ता",
        optionalLabel: "(पर्यायी)",
        confirmPassword: "पासवर्डची पुष्टी करा",
        reenterPassword: "तुमचा पासवर्ड पुन्हा प्रविष्ट करा",
        createPasswordHint: "पासवर्ड तयार करा (किमान 6 अक्षरे)",
        creatingAccount: "खाते तयार होत आहे...",
        createAccountBtn: "खाते तयार करा",
        alreadyHaveAccount: "आधीच खाते आहे?",
        signInLink: "साइन इन करा",
        registerTagline1: "चांगला चारा",
        registerTagline2: "सुरू होतो",
        registerTagline3: "चांगल्या अंतर्दृष्टीने.",
        registerTaglineDesc: "साध्या, शेतकरी-अनुकूल शिफारसींसह चारा आणि सायलेज गुणवत्ता समजून घ्या.",

        // Analysis Result
        analysisComplete: "विश्लेषण पूर्ण",
        testIdLabel: "चाचणी आयडी",
        qualityAnalysisResult: "गुणवत्ता विश्लेषण निकाल",
        feedSampleEvaluated: "तुमच्या चाऱ्याच्या नमुन्याचे सर्व गुणवत्ता आणि सुरक्षा मापदंडांवर मूल्यांकन केले गेले आहे.",
        silageSampleEvaluated: "तुमच्या सायलेज नमुन्याचे सर्व गुणवत्ता आणि सुरक्षा मापदंडांवर मूल्यांकन केले गेले आहे.",
        overallQuality: "एकूण गुणवत्ता",
        aiVisualScreening: "AI दृश्य विसंगती आणि दोष तपासणी",
        visualStatus: "दृश्य स्थिती",
        mould: "बुरशी",
        discolor: "रंग बदल",
        foreignMat: "परकीय साहित्य",
        total: "एकूण",
        detectedAnomalies: "आढळलेल्या विसंगती",
        anomaly: "विसंगती",
        confidence: "विश्वास",
        location: "स्थान",
        measuredParameters: "मोजलेले मापदंड",
        noReadingsEntered: "कोणतीही भौतिक रीडिंग प्रविष्ट केलेली नाही. दृश्य मापदंडांवर आधारित तपासणी.",
        moistureLabel: "ओलावा",
        crudeProteinLabel: "कच्चे प्रथिने",
        crudeFiberLabel: "कच्चे तंतू",
        aflatoxinLabel: "अफ्लाटॉक्सिन (ppb)",
        phLevelLabel: "pH स्तर",
        temperatureLabel: "तापमान",
        warningLabel: "(इशारा)",
        safeLabel: "(सुरक्षित)",
        recommendations: "शिफारसी",
        sampleSuitable: "उपलब्ध इनपुटच्या आधारे नमुना योग्य दिसतो.",
        viewDetailedAdvisory: "तपशीलवार सल्ला पाहा",
        newAnalysisBtn2: "नवीन विश्लेषण",
        downloadPDFReport: "PDF अहवाल डाउनलोड करा",
        generatingPDFBtn: "PDF तयार होत आहे...",

        dashboard: "डॅशबोर्ड",
        newAnalysis: "नवीन विश्लेषण",
        testHistory: "चाचणी इतिहास",
        reports: "अहवाल",
        profile: "प्रोफाइल",
        settings: "सेटिंग्ज",
        logout: "लॉग आउट",
        dashboardLabel: "डॅशबोर्ड",
        goodDay: "नमस्कार",
        dashboardSubtitle: "येथे तुमचे रिअल-टाइम गुणवत्ता विश्लेषण अवलोकन आहे.",
        newAnalysisBtn: "नवीन विश्लेषण",
        totalTests: "एकूण चाचण्या",
        goodQuality: "चांगली गुणवत्ता",
        averageQuality: "सरासरी गुणवत्ता",
        poorQuality: "खराब गुणवत्ता",
        completedTests: "पूर्ण चाचण्या",
        noTestsYet: "अद्याप कोणत्याही चाचण्या नाहीत",
        ofTotalTests: "% एकूण चाचण्यांपैकी",
        recentTests: "अलीकडील चाचण्या",
        latestAnalyses: "तुमचे नवीनतम गुणवत्ता विश्लेषण",
        viewAll: "सर्व पहा",
        noRecentTests: "कोणत्याही अलीकडील चाचण्या आढळल्या नाहीत.",
        startFirstTest: "तुमची पहिली चाचणी सुरू करा",
        qualityOverview: "गुणवत्ता अवलोकन",
        testDistribution: "सध्याचे चाचणी वितरण",
        tests: "चाचण्या",
        good: "चांगले",
        average: "सरासरी",
        poor: "खराब",
        qualityTip: "गुणवत्ता देखरेख सूचना",
        qualityTipText: "दृश्य गुणवत्ता निर्देशकांसह ओलावा, pH आणि साठवण परिस्थितीचे नियमितपणे निरीक्षण करा.",
        accountLabel: "खाते",
        myProfile: "माझी प्रोफाइल",
        profileSubtitle: "तुमचे शेतकरी खाते आणि शेत माहिती व्यवस्थापित करा.",
        fullName: "पूर्ण नाव",
        emailReadOnly: "ईमेल (केवळ वाचण्यासाठी)",
        mobileNumber: "मोबाइल नंबर",
        farmInformation: "शेत माहिती",
        saveChanges: "बदल जतन करा",
        savingChanges: "जतन करत आहे...",
        profileUpdated: "प्रोफाइल यशस्वीरित्या अपडेट झाली!",
        enterFullName: "तुमचे पूर्ण नाव प्रविष्ट करा",
        enterMobile: "मोबाइल नंबर प्रविष्ट करा",
        enterFarmInfo: "तुमच्या शेत, स्थान किंवा पशुधनाबद्दल तपशील प्रविष्ट करा",
        settingsSection: "सेटिंग्ज",
        languageSection: "भाषा",
        languageSectionDesc: "संपूर्ण ॲपसाठी तुमची पसंतीची भाषा निवडा.",
        notificationsLabel: "सूचना",
        notificationsDesc: "गुणवत्ता विश्लेषण सूचना प्राप्त करा.",
        offlineModeLabel: "ऑफलाइन मोड",
        offlineModeDesc: "ऑफलाइन असताना चाचण्या स्थानिक पातळीवर साठवा.",
        settingsSaved: "सेटिंग्ज जतन झाल्या!",
        settingsLabel: "सेटिंग्ज",
        appSettings: "अॅप्लिकेशन सेटिंग्ज",
        customizeExperience: "तुमचा AgriFeed AI अनुभव सानुकूलित करा.",
        chooseLanguage: "तुमची पसंतीची भाषा निवडा.",
        features: "वैशिष्ट्ये",
        howItWorks: "हे कसे कार्य करते",
        about: "आमच्याबद्दल",
        login: "लॉग इन",
        getStarted: "सुरू करा",
        heroHeadline1: "स्मार्ट चारा.",
        heroHeadline2: "निरोगी पशुधन.",
        heroHeadline3: "चांगले निर्णय.",
        heroDesc: "AI-चालित प्रतिमा विश्लेषण आणि चाचणी रीडिंगचा वापर करून गुरांचे चारा आणि सायलेजची गुणवत्ता विश्लेषण करा.",
        startAnalyzing: "विश्लेषण सुरू करा",
        learnMore: "अधिक जाणून घ्या",
        featuresLabel: "वैशिष्ट्ये",
        featuresHeading: "गुणवत्ता मूल्यांकनासाठी सर्व काही",
        featuresSubheading: "चारा आणि सायलेज मूल्यांकन सोपे करण्यासाठी एक सोपा डिजिटल व्यासपीठ.",
        imageAnalysis: "प्रतिमा विश्लेषण",
        imageAnalysisDesc: "AI-आधारित दृश्य विश्लेषणासाठी नमुना प्रतिमा अपलोड किंवा कॅप्चर करा.",
        aiClassification: "AI वर्गीकरण",
        aiClassificationDesc: "प्रशिक्षित संगणक दृष्टी मॉडेल वापरून चारा आणि सायलेज परिस्थिती वर्गीकृत करा.",
        qualityEvaluation: "गुणवत्ता मूल्यांकन",
        qualityEvaluationDesc: "सर्वसमावेशक स्कोअरिंगसाठी AI परिणाम ऐच्छिक चाचणी रीडिंगसह एकत्र करा.",
        reportsHistory: "अहवाल आणि इतिहास",
        reportsHistoryDesc: "मागील चाचण्या ट्रॅक करा आणि कालांतराने गुणवत्ता ट्रेंडचे निरीक्षण करा.",
        howItWorksLabel: "हे कसे कार्य करते",
        fromSampleToRec: "नमुन्यापासून शिफारसीपर्यंत",
        step1Title: "नमुना अपलोड करा",
        step1Desc: "चारा किंवा सायलेजची प्रतिमा कॅप्चर किंवा अपलोड करा.",
        step2Title: "AI विश्लेषण",
        step2Desc: "AI मॉडेल दृश्यमान वैशिष्ट्यांचे विश्लेषण करते.",
        step3Title: "गुणवत्ता तपासणी",
        step3Desc: "AI निष्कर्ष आणि रीडिंगचे एकत्र मूल्यांकन केले जाते.",
        step4Title: "सल्ला मिळवा",
        step4Desc: "एक साधा निकाल आणि शिफारस प्राप्त करा.",
        ctaHeading: "तुमच्या नमुन्याचे विश्लेषण करण्यासाठी तयार आहात?",
        ctaSubheading: "आजच तुमचे डिजिटल चारा आणि सायलेज गुणवत्ता मूल्यांकन सुरू करा.",
        footerRight: "AI-आधारित चारा आणि सायलेज गुणवत्ता विश्लेषण",

        // Advisory / Recommendations
        advisoryLabel: "सल्ला",
        advisoryHeading: "शिफारसी",
        advisorySubtitle: "वर आधारित व्यावहारिक मार्गदर्शन",
        advisoryYourResults: "तुमचे विश्लेषण निकाल",
        currentAssessment: "सध्याचे मूल्यांकन",
        qualityWord: "गुणवत्ता",
        recommendationNum: "शिफारस",
        importantCardTitle: "महत्त्वाचे",
        importantCardDesc: "हा ॲप्लिकेशन प्राथमिक तपासणी आणि सल्लागार माहिती प्रदान करतो. हे तपशीलवार पोषण किंवा विष विश्लेषणासाठी प्रयोगशाळा चाचणीची जागा घेत नाही.",
        tipCardTitle: "गुणवत्ता देखरेख टीप",
        tipCardDesc: "वारंवार उद्भवणाऱ्या साठवणूक किंवा हाताळणीच्या समस्या ओळखण्यासाठी कालांतराने चारा आणि सायलेज गुणवत्तेच्या नोंदी ठेवा.",
        defaultAdvice1Title: "योग्य साठवण सुरू ठेवा",
        defaultAdvice1Desc: "चाऱ्याचे अति ओलावा आणि अयोग्य साठवण परिस्थितीपासून संरक्षण करा.",
        defaultAdvice2Title: "गुणवत्तेचे नियमित निरीक्षण करा",
        defaultAdvice2Desc: "हंगामी ट्रेंड ओळखण्यासाठी नियमित दृश्य तपासणी करा आणि उपलब्ध नोंदी ठेवा.",
        defaultAdvice3Title: "शंकास्पद समस्यांची खात्री करा",
        defaultAdvice3Desc: "बुरशी, नासाडी किंवा दूषितपणाचा संशय असल्यास, योग्य प्रयोगशाळा चाचणीचा विचार करा.",
    },

    Kannada: {
        // Sample Selection
        newAnalysisLabel: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
        whatToAnalyze: "ನೀವು ಏನನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಬಯಸುತ್ತೀರಿ?",
        selectSampleType: "ನೀವು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಬಯಸುವ ಮಾದರಿ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        feed: "ಮೇವು",
        feedDesc: "ತೇವಾಂಶ, ಪ್ರೋಟೀನ್ ಮತ್ತು ನಾರು ಮುಂತಾದ ಐಚ್ಛಿಕ ಅಳತೆಗಳೊಂದಿಗೆ ಚಿತ್ರ ಬಳಸಿ ಮೇವಿನ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಿಸಿ.",
        startFeedAnalysis: "ಮೇವು ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
        silage: "ಸೈಲೇಜ್",
        silageDesc: "pH, ತೇವಾಂಶ ಮತ್ತು ತಾಪಮಾನದಂತಹ ರೀಡಿಂಗ್‌ಗಳೊಂದಿಗೆ ದೃಶ್ಯ ಗುಣಲಕ್ಷಣಗಳನ್ನು ಬಳಸಿ ಸೈಲೇಜ್ ಸ್ಥಿತಿ ವಿಶ್ಲೇಷಿಸಿ.",
        startSilageAnalysis: "ಸೈಲೇಜ್ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
        backToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        changeSample: "ಮಾದರಿ ಬದಲಿಸಿ",
        feedAnalysisLabel: "ಮೇವು ವಿಶ್ಲೇಷಣೆ",
        analyzeFeedQuality: "ಮೇವಿನ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಿಸಿ",
        feedAnalysisDesc: "ಸ್ವಯಂಚಾಲಿತ ದೃಶ್ಯ ದೋಷ ಪತ್ತೆಗಾಗಿ (ಅಚ್ಚು, ಬಣ್ಣ ಬದಲಾವಣೆ, ವಿದೇಶಿ ವಸ್ತು) ನಿಮ್ಮ ಮೇವಿನ ಮಾದರಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        fullAssessmentImage: "ಸಂಪೂರ್ಣ ಮೌಲ್ಯಮಾಪನ ಮಾದರಿ ಚಿತ್ರ",
        required: "ಅಗತ್ಯ",
        uploadFeedImageHint: "ನಿಮ್ಮ ಶಾಶ್ವತ ಪರೀಕ್ಷಾ ವರದಿಗಾಗಿ ಮೇವಿನ ಮಾದರಿಯ ಸ್ಪಷ್ಟ, ಉತ್ತಮ ಬೆಳಕಿನ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        clickToUploadFeed: "ಮೇವಿನ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
        imageFormatHint: "PNG, JPG ಅಥವಾ JPEG — ಗರಿಷ್ಠ 15MB",
        imageRequired: "ವಿಶ್ಲೇಷಿಸುವ ಮೊದಲು ಮಾದರಿ ಚಿತ್ರ ಅಗತ್ಯ.",
        changeImage: "ಚಿತ್ರ ಬದಲಿಸಿ",
        chooseImageFile: "ಚಿತ್ರ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ",
        useCamera: "ಕ್ಯಾಮೆರಾ ಬಳಸಿ",
        testReadings: "ಪರೀಕ್ಷಾ ರೀಡಿಂಗ್‌ಗಳು ಮತ್ತು ನಿಯತಾಂಕಗಳು",
        optionalReadings: "ಐಚ್ಛಿಕ — ಲಭ್ಯ ಪ್ರಯೋಗಾಲಯ ರೀಡಿಂಗ್‌ಗಳನ್ನು ನಮೂದಿಸಿ.",
        moisture: "ತೇವಾಂಶ (%)",
        crudeProtein: "ಕಚ್ಚಾ ಪ್ರೋಟೀನ್ (%)",
        crudeFiber: "ಕಚ್ಚಾ ನಾರು (%)",
        aflatoxin: "ಅಫ್ಲಟಾಕ್ಸಿನ್ (ppb)",
        phValue: "pH ಮೌಲ್ಯ",
        feedInfoBox: "ಪರೀಕ್ಷಾ ರೀಡಿಂಗ್‌ಗಳು ಐಚ್ಛಿಕ. ಸಿಸ್ಟಮ್ ಅವುಗಳಿಲ್ಲದೆ ಪ್ರಾಥಮಿಕ ತಪಾಸಣೆ ಮಾಡಬಹುದು.",
        generateReport: "ಸಂಪೂರ್ಣ ವರದಿ ರಚಿಸಿ",
        analyzingFeed: "ಮೇವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ವರದಿ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        uploadToEnable: "ವರದಿ ರಚಿಸಲು ಮಾದರಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        silageAnalysisLabel: "ಸೈಲೇಜ್ ವಿಶ್ಲೇಷಣೆ",
        analyzeSilageQuality: "ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಿಸಿ",
        silageAnalysisDesc: "ಸ್ವಯಂಚಾಲಿತ ದೃಶ್ಯ ದೋಷ ಪತ್ತೆಗಾಗಿ ನಿಮ್ಮ ಸೈಲೇಜ್ ಮಾದರಿ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        uploadSilageImageHint: "ನಿಮ್ಮ ಶಾಶ್ವತ ಪರೀಕ್ಷಾ ವರದಿಗಾಗಿ ಸೈಲೇಜ್ ಮಾದರಿಯ ಸ್ಪಷ್ಟ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        clickToUploadSilage: "ಸೈಲೇಜ್ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
        pitTemperature: "ಪಿಟ್ ತಾಪಮಾನ (°C)",
        silageInfoBox: "ಫಲಿತಾಂಶ ಒಂದು ಪ್ರಾಥಮಿಕ ತಪಾಸಣೆ ಮತ್ತು ಪ್ರಯೋಗಾಲಯ ಪರೀಕ್ಷೆಯನ್ನು ಬದಲಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.",
        analyzingSilage: "ಸೈಲೇಜ್ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ವರದಿ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        reportsLabel: "ವರದಿಗಳು",
        analysisReports: "ವಿಶ್ಲೇಷಣೆ ವರದಿಗಳು",
        reportsSubtitle: "ಅಧಿಕೃತ PDF ಗುಣಮಟ್ಟ ಮತ್ತು ಸುರಕ್ಷತೆ ಮೌಲ್ಯಮಾಪನ ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
        noReports: "ಇನ್ನೂ ಯಾವುದೇ ವರದಿ ರಚಿಸಲಾಗಿಲ್ಲ. ವರದಿ ರಚಿಸಲು ಹೊಸ ವಿಶ್ಲೇಷಣೆ ಮಾಡಿ.",
        feedQualityReport: "ಮೇವಿನ ಗುಣಮಟ್ಟ ವರದಿ",
        silageQualityReport: "ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ವರದಿ",
        testId: "ಪರೀಕ್ಷಾ ID",
        downloadPDF: "PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        generatingPDF: "PDF ರಚಿಸಲಾಗುತ್ತಿದೆ...",

        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        newAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
        testHistory: "ಪರೀಕ್ಷೆ ಇತಿಹಾಸ",
        reports: "ವರದಿಗಳು",
        profile: "ಪ್ರೊಫೈಲ್",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        logout: "ಲಾಗ್ ಔಟ್",
        dashboardLabel: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        goodDay: "ನಮಸ್ಕಾರ",
        dashboardSubtitle: "ಇಲ್ಲಿ ನಿಮ್ಮ ರಿಯಲ್-ಟೈಮ್ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆ ಅವಲೋಕನ ಇದೆ.",
        newAnalysisBtn: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
        totalTests: "ಒಟ್ಟು ಪರೀಕ್ಷೆಗಳು",
        goodQuality: "ಉತ್ತಮ ಗುಣಮಟ್ಟ",
        averageQuality: "ಸರಾಸರಿ ಗುಣಮಟ್ಟ",
        poorQuality: "ಕಳಪೆ ಗುಣಮಟ್ಟ",
        completedTests: "ಪೂರ್ಣ ಪರೀಕ್ಷೆಗಳು",
        noTestsYet: "ಇನ್ನೂ ಪರೀಕ್ಷೆಗಳಿಲ್ಲ",
        ofTotalTests: "% ಒಟ್ಟು ಪರೀಕ್ಷೆಗಳಲ್ಲಿ",
        recentTests: "ಇತ್ತೀಚಿನ ಪರೀಕ್ಷೆಗಳು",
        latestAnalyses: "ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆಗಳು",
        viewAll: "ಎಲ್ಲ ನೋಡಿ",
        noRecentTests: "ಇತ್ತೀಚಿನ ಪರೀಕ್ಷೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
        startFirstTest: "ನಿಮ್ಮ ಮೊದಲ ಪರೀಕ್ಷೆ ಪ್ರಾರಂಭಿಸಿ",
        qualityOverview: "ಗುಣಮಟ್ಟ ಅವಲೋಕನ",
        testDistribution: "ಪ್ರಸ್ತುತ ಪರೀಕ್ಷೆ ವಿತರಣೆ",
        tests: "ಪರೀಕ್ಷೆಗಳು",
        good: "ಉತ್ತಮ",
        average: "ಸರಾಸರಿ",
        poor: "ಕಳಪೆ",
        qualityTip: "ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ ಸಲಹೆ",
        qualityTipText: "ದೃಶ್ಯ ಗುಣಮಟ್ಟ ಸೂಚಕಗಳ ಜೊತೆಗೆ ತೇವಾಂಶ, pH ಮತ್ತು ಸಂಗ್ರಹ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.",
        accountLabel: "ಖಾತೆ",
        myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
        profileSubtitle: "ನಿಮ್ಮ ರೈತ ಖಾತೆ ಮತ್ತು ಕೃಷಿ ಮಾಹಿತಿ ನಿರ್ವಹಿಸಿ.",
        fullName: "ಪೂರ್ಣ ಹೆಸರು",
        emailReadOnly: "ಇಮೇಲ್ (ಓದಲು ಮಾತ್ರ)",
        mobileNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        farmInformation: "ಕೃಷಿ ಮಾಹಿತಿ",
        saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        savingChanges: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
        profileUpdated: "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
        enterFullName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ",
        enterMobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
        enterFarmInfo: "ನಿಮ್ಮ ಕೃಷಿ, ಸ್ಥಳ ಅಥವಾ ದನದ ಹಿಂಡಿನ ಬಗ್ಗೆ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
        settingsSection: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        languageSection: "ಭಾಷೆ",
        languageSectionDesc: "ಇಡೀ ಅಪ್ಲಿಕೇಶನ್‌ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ.",
        notificationsLabel: "ಅಧಿಸೂಚನೆಗಳು",
        notificationsDesc: "ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.",
        offlineModeLabel: "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
        offlineModeDesc: "ಆಫ್‌ಲೈನ್ ಆಗಿರುವಾಗ ಪರೀಕ್ಷೆಗಳನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಸಂಗ್ರಹಿಸಿ.",
        settingsSaved: "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ!",
        settingsLabel: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        appSettings: "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        customizeExperience: "ನಿಮ್ಮ AgriFeed AI ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ.",
        chooseLanguage: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ.",
        features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
        howItWorks: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
        about: "ನಮ್ಮ ಬಗ್ಗೆ",
        login: "ಲಾಗಿನ್",
        getStarted: "ಪ್ರಾರಂಭಿಸಿ",
        heroHeadline1: "ಸ್ಮಾರ್ಟ್ ಮೇವು.",
        heroHeadline2: "ಆರೋಗ್ಯಕರ ಜಾನುವಾರು.",
        heroHeadline3: "ಉತ್ತಮ ನಿರ್ಧಾರಗಳು.",
        heroDesc: "AI-ಚಾಲಿತ ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಪರೀಕ್ಷಾ ರೀಡಿಂಗ್‌ಗಳನ್ನು ಬಳಸಿ ಜಾನುವಾರು ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟವನ್ನು ವಿಶ್ಲೇಷಿಸಿ.",
        startAnalyzing: "ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
        learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
        featuresLabel: "ವೈಶಿಷ್ಟ್ಯಗಳು",
        featuresHeading: "ಗುಣಮಟ್ಟ ಮೌಲ್ಯಮಾಪನಕ್ಕೆ ಎಲ್ಲವೂ",
        featuresSubheading: "ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಮೌಲ್ಯಮಾಪನವನ್ನು ಸುಲಭಗೊಳಿಸಲು ಸರಳ ಡಿಜಿಟಲ್ ವೇದಿಕೆ.",
        imageAnalysis: "ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ",
        imageAnalysisDesc: "AI-ಆಧಾರಿತ ದೃಶ್ಯ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಮಾದರಿ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಅಥವಾ ಕ್ಯಾಪ್ಚರ್ ಮಾಡಿ.",
        aiClassification: "AI ವರ್ಗೀಕರಣ",
        aiClassificationDesc: "ತರಬೇತಿ ಪಡೆದ ಕಂಪ್ಯೂಟರ್ ದೃಷ್ಟಿ ಮಾದರಿಗಳನ್ನು ಬಳಸಿ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ವರ್ಗೀಕರಿಸಿ.",
        qualityEvaluation: "ಗುಣಮಟ್ಟ ಮೌಲ್ಯಮಾಪನ",
        qualityEvaluationDesc: "ಸಮಗ್ರ ಸ್ಕೋರಿಂಗ್‌ಗಾಗಿ AI ಫಲಿತಾಂಶಗಳನ್ನು ಐಚ್ಛಿಕ ಪರೀಕ್ಷಾ ರೀಡಿಂಗ್‌ಗಳೊಂದಿಗೆ ಸಂಯೋಜಿಸಿ.",
        reportsHistory: "ವರದಿಗಳು ಮತ್ತು ಇತಿಹಾಸ",
        reportsHistoryDesc: "ಹಿಂದಿನ ಪರೀಕ್ಷೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಕಾಲಾಂತರದಲ್ಲಿ ಗುಣಮಟ್ಟ ಪ್ರವೃತ್ತಿಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.",
        howItWorksLabel: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
        fromSampleToRec: "ಮಾದರಿಯಿಂದ ಶಿಫಾರಸಿನವರೆಗೆ",
        step1Title: "ಮಾದರಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        step1Desc: "ಮೇವು ಅಥವಾ ಸೈಲೇಜ್ ಚಿತ್ರವನ್ನು ಕ್ಯಾಪ್ಚರ್ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        step2Title: "AI ವಿಶ್ಲೇಷಣೆ",
        step2Desc: "AI ಮಾದರಿ ಗೋಚರ ಗುಣಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.",
        step3Title: "ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ",
        step3Desc: "AI ಸಂಶೋಧನೆಗಳು ಮತ್ತು ರೀಡಿಂಗ್‌ಗಳನ್ನು ಒಟ್ಟಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತದೆ.",
        step4Title: "ಸಲಹೆ ಪಡೆಯಿರಿ",
        step4Desc: "ಸರಳ ಫಲಿತಾಂಶ ಮತ್ತು ಶಿಫಾರಸು ಸ್ವೀಕರಿಸಿ.",
        ctaHeading: "ನಿಮ್ಮ ಮಾದರಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
        ctaSubheading: "ಇಂದೇ ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ.",
        footerRight: "AI-ಆಧಾರಿತ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆ",

        selectLanguage: "ಭಾಷೆ",
        backToHome: "← ಮನೆಗೆ ಹಿಂತಿರುಗಿ",
        welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
        loginSubtitle: "ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        emailOrMobile: "ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        password: "ಪಾಸ್‌ವರ್ಡ್",
        rememberMe: "ನನ್ನನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಿ",
        signIn: "ಸೈನ್ ಇನ್",
        signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
        noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
        createAccount: "ಖಾತೆ ರಚಿಸಿ",
        loginTagline1: "ಉತ್ತಮ ಗುಣಮಟ್ಟ.",
        loginTagline2: "ಉತ್ತಮ ನಿರ್ಧಾರಗಳು.",
        loginTaglineDesc: "ನಿಮ್ಮ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ತ್ವರಿತವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು AI-ಚಾಲಿತ ವಿಶ್ಲೇಷಣೆ ಬಳಸಿ.",
        enterEmailOrMobile: "you@example.com ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        enterPassword: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
        createYourAccount: "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ",
        registerSubtitle: "ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ.",
        emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
        optionalLabel: "(ಐಚ್ಛಿಕ)",
        confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
        reenterPassword: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೆ ನಮೂದಿಸಿ",
        createPasswordHint: "ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ (ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು)",
        creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        createAccountBtn: "ಖಾತೆ ರಚಿಸಿ",
        alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
        signInLink: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
        registerTagline1: "ಉತ್ತಮ ಮೇವು",
        registerTagline2: "ಪ್ರಾರಂಭವಾಗುತ್ತದೆ",
        registerTagline3: "ಉತ್ತಮ ಒಳನೋಟದಿಂದ.",
        registerTaglineDesc: "ಸರಳ, ರೈತ-ಸ್ನೇಹಿ ಶಿಫಾರಸುಗಳೊಂದಿಗೆ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
        analysisComplete: "ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣ",
        testIdLabel: "ಪರೀಕ್ಷಾ ID",
        qualityAnalysisResult: "ಗುಣಮಟ್ಟ ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ",
        feedSampleEvaluated: "ನಿಮ್ಮ ಮೇವಿನ ಮಾದರಿಯನ್ನು ಎಲ್ಲ ಗುಣಮಟ್ಟ ಮತ್ತು ಸುರಕ್ಷತೆ ನಿಯತಾಂಕಗಳಲ್ಲಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿದೆ.",
        silageSampleEvaluated: "ನಿಮ್ಮ ಸೈಲೇಜ್ ಮಾದರಿಯನ್ನು ಎಲ್ಲ ಗುಣಮಟ್ಟ ಮತ್ತು ಸುರಕ್ಷತೆ ನಿಯತಾಂಕಗಳಲ್ಲಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿದೆ.",
        overallQuality: "ಒಟ್ಟಾರೆ ಗುಣಮಟ್ಟ",
        aiVisualScreening: "AI ದೃಶ್ಯ ವೈಪರೀತ್ಯ ಮತ್ತು ದೋಷ ತಪಾಸಣೆ",
        visualStatus: "ದೃಶ್ಯ ಸ್ಥಿತಿ",
        mould: "ಅಚ್ಚು",
        discolor: "ಬಣ್ಣ ಬದಲಾವಣೆ",
        foreignMat: "ವಿದೇಶಿ ವಸ್ತು",
        total: "ಒಟ್ಟು",
        detectedAnomalies: "ಪತ್ತೆಯಾದ ವೈಪರೀತ್ಯಗಳು",
        anomaly: "ವೈಪರೀತ್ಯ",
        confidence: "ವಿಶ್ವಾಸ",
        location: "ಸ್ಥಳ",
        measuredParameters: "ಅಳೆದ ನಿಯತಾಂಕಗಳು",
        noReadingsEntered: "ಯಾವುದೇ ಭೌತಿಕ ರೀಡಿಂಗ್ ನಮೂದಿಸಲಾಗಿಲ್ಲ. ದೃಶ್ಯ ನಿಯತಾಂಕಗಳ ಆಧಾರದ ಮೇಲೆ ತಪಾಸಣೆ.",
        moistureLabel: "ತೇವಾಂಶ",
        crudeProteinLabel: "ಕಚ್ಚಾ ಪ್ರೋಟೀನ್",
        crudeFiberLabel: "ಕಚ್ಚಾ ನಾರು",
        aflatoxinLabel: "ಅಫ್ಲಟಾಕ್ಸಿನ್ (ppb)",
        phLevelLabel: "pH ಮಟ್ಟ",
        temperatureLabel: "ತಾಪಮಾನ",
        warningLabel: "(ಎಚ್ಚರಿಕೆ)",
        safeLabel: "(ಸುರಕ್ಷಿತ)",
        recommendations: "ಶಿಫಾರಸುಗಳು",
        sampleSuitable: "ಲಭ್ಯ ಇನ್‌ಪುಟ್‌ಗಳ ಆಧಾರದ ಮೇಲೆ ಮಾದರಿ ಸೂಕ್ತವಾಗಿದೆ.",
        viewDetailedAdvisory: "ವಿವರವಾದ ಸಲಹೆ ವೀಕ್ಷಿಸಿ",
        newAnalysisBtn2: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
        downloadPDFReport: "PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        generatingPDFBtn: "PDF ರಚಿಸಲಾಗುತ್ತಿದೆ...",

        // Advisory / Recommendations
        advisoryLabel: "ಸಲಹೆ",
        advisoryHeading: "ಶಿಫಾರಸುಗಳು",
        advisorySubtitle: "ಆಧಾರಿತ ಪ್ರಾಯೋಗಿಕ ಮಾರ್ಗದರ್ಶನ",
        advisoryYourResults: "ನಿಮ್ಮ ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು",
        currentAssessment: "ಪ್ರಸ್ತುತ ಮೌಲ್ಯಮಾಪನ",
        qualityWord: "ಗುಣಮಟ್ಟ",
        recommendationNum: "ಶಿಫಾರಸು",
        importantCardTitle: "ಮುಖ್ಯ",
        importantCardDesc: "ಈ ಅಪ್ಲಿಕೇಶನ್ ಪ್ರಾಥಮಿಕ ತಪಾಸಣೆ ಮತ್ತು ಸಲಹಾ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸುತ್ತದೆ. ಇದು ವಿವರವಾದ ಪೌಷ್ಟಿಕ ಅಥವಾ ವಿಷ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಪ್ರಯೋಗಾಲಯ ಪರೀಕ್ಷೆಯನ್ನು ಬದಲಾಯಿಸುವುದಿಲ್ಲ.",
        tipCardTitle: "ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ ಸಲಹೆ",
        tipCardDesc: "ಮರುಕಳಿಸುವ ಸಂಗ್ರಹಣೆ ಅಥವಾ ನಿರ್ವಹಣೆ ಸಮಸ್ಯೆಗಳನ್ನು ಗುರುತಿಸಲು ಕಾಲಾಂತರದಲ್ಲಿ ಮೇವು ಮತ್ತು ಸೈಲೇಜ್ ಗುಣಮಟ್ಟದ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
        defaultAdvice1Title: "ಸರಿಯಾದ ಸಂಗ್ರಹಣೆ ಮುಂದುವರಿಸಿ",
        defaultAdvice1Desc: "ಅತಿಯಾದ ತೇವಾಂಶ ಮತ್ತು ಸೂಕ್ತವಲ್ಲದ ಸಂಗ್ರಹಣಾ ಪರಿಸ್ಥಿತಿಗಳಿಂದ ಮೇವನ್ನು ರಕ್ಷಿಸಿ.",
        defaultAdvice2Title: "ನಿಯಮಿತವಾಗಿ ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
        defaultAdvice2Desc: "ಋತುಮಾನದ ಪ್ರವೃತ್ತಿಗಳನ್ನು ಗುರುತಿಸಲು ನಿಯಮಿತ ದೃಶ್ಯ ತಪಾಸಣೆ ನಡೆಸಿ ಮತ್ತು ಲಭ್ಯವಿರುವ ಮಾಪನಗಳನ್ನು ದಾಖಲಿಸಿ.",
        defaultAdvice3Title: "ಅನುಮಾನಾಸ್ಪದ ಸಮಸ್ಯೆಗಳನ್ನು ದೃಢೀಕರಿಸಿ",
        defaultAdvice3Desc: "ಶಿಲೀಂಧ್ರ, ಹಾಳಾಗುವಿಕೆ ಅಥವಾ ಮಾಲಿನ್ಯ ಶಂಕೆಯಿದ್ದಲ್ಲಿ, ಸೂಕ್ತ ಪ್ರಯೋಗಾಲಯ ಪರೀಕ್ಷೆಯನ್ನು ಪರಿಗಣಿಸಿ.",
    },
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem("appLanguage") || "English";
    });

    useEffect(() => {
        localStorage.setItem("appLanguage", language);
    }, [language]);

    const t = translations[language] || translations["English"];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
    return ctx;
}
